name: 'PR CI'

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  flutter_test:
    name: Test (kg-wallet-core)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/flutter_day_2_flavor
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'
      - name: Flutter Test
        run: |
          flutter pub get
          flutter test
